### ISSUE TITLE
QFT Adder not supported despite containing only supported gates

### ISSUE THREAD

**Issue by fvoichick** [onestruggler/quipper-qasm#3]
I wrote the following Quipper file:

    import Quipper
    import Quipper.Libraries.Arith
    import Quipper.Libraries.QFTAdd
    
    main :: IO ()
    main = print_generic ASCII qft_add_in_place example_num example_num
      where example_num = qshape (intm 2 0)

This produced the following output:

    Inputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit
    Comment[""](0:"a[0]", 1:"a[1]", 2:"b[0]", 3:"b[1]")
    Subroutine["QFT", shape "([Q,Q],())"] (2,3) -> (3,2) with nocontrol
    QRot["R(2pi/%)",2.0](2) with controls=[+0]
    QRot["R(2pi/%)",4.0](2) with controls=[+1]
    QRot["R(2pi/%)",2.0](3) with controls=[+1]
    Subroutine["QFT", shape "([Q,Q],())"]* (3,2) -> (2,3) with nocontrol
    Comment[""](0:"a[0]", 1:"a[1]", 2:"b[0]", 3:"b[1]")
    Outputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit
    
    Subroutine: "QFT"
    Shape: "([Q,Q],())"
    Controllable: yes
    Inputs: 0:Qbit, 1:Qbit
    Comment["ENTER: qft_big_endian"](0:"qs[0]", 1:"qs[1]")
    QGate["H"](0)
    QRot["R(2pi/%)",4.0](0) with controls=[+1]
    QGate["H"](1)
    Comment["EXIT: qft_big_endian"](0:"qs[1]", 1:"qs[0]")
    Outputs: 1:Qbit, 0:Qbit

However, when I use the converter I get the following error message:

    QasmPrinting: "R(2pi/%)" Gate not supported
    CallStack (from HasCallStack):
      error, called at QasmPrinting.hs:261:14 in main:Main

This error message doesn't make sense to me because the same gates are used in the normal QFT, and that converts fine, but the QFT _adder_ is failing.

**Comment by onestruggler** [comment]
-inline option works for me. This is due to QFT in adder circuit is a subroutine, and for some reason the trim_ctrl transfromer didn't get applied to subroutines, which results that the control of  "R(2pi/%)"  didn't get removed. But our Qasmprinting only support no-control version of "R(2pi/%)". I will look into it.

**Comment by fvoichick** [comment]
Okay, `-inline` works for me too. I hadn’t tried that because [your webpage](https://www.mathstat.dal.ca/~xbian/QasmTrans/index.php) made it seem like that was only for non-unitary subroutines.

**Comment by onestruggler** [comment]
Yeah, there is definitely something unsatisfying there. I thought -inline is only needed for non-unitary subroutines. But it turns out not so. 

I looked into the codes, someting called a "dynamic transformer"  (vs. transformer) supports recursive application to subroutine, which can solve this problem. But I will leave it as a future work. 

Thanks for finding those bugs.
